# api-gateway/src/main/resources/application.yml
server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: saga-orchestrator
          uri: http://localhost:8089
          predicates:
            - Path=/saga/**
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/inventory/**
        - id: discount-service
          uri: http://localhost:8084
          predicates:
            - Path=/discounts/**



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
