server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
        - id: discount-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/discounts/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework: INFO
