# payment-service/src/main/resources/application.yml
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernateDemoDB
    username: postgres
    password: hamidreza80
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
  kafka:
    consumer:
      group-id: payment-service-group
    producer:
      acks: all
logging:
  level:
    org.springframework: INFO
    org.springframework.kafka: INFO
