server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hibernateDemoDB
    username: postgres
    password: hamidreza80
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernateDemoDB
    username: postgres
    password: hamidreza80
  main:
    allow-bean-definition-overriding: true

product-service:
  url: http://localhost:8081/api/products

discount-service:
  url: http://localhost:8082/api/discounts

logging:
  level:
    org.springframework: INFO
