server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hibernateDemoDB
    username: postgres
    password: hamidreza80
    schema-generation:
      create-schemas: always
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernateDemoDB
    username: postgres
    password: hamidreza80
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework: INFO
